language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - run_simple_service
before_install:
- echo "installing kubectl"
- curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- kubectl version --client
- echo "installing KinD"
- curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
- sudo chmod +x ./kind
- sudo mv ./kind /usr/local/bin/kind
- kind --version
- kind create cluster --config ./kind-config.yaml
- sleep 2m
- kubectl get nodes
script:
- kubectl create deployment pinger --replicas=3 --image=reselbob/pinger
- kubectl create service nodeport pinger --tcp=3000:3000
- sleep 2m
- kubectl get svc -o wide
- kubectl get pods -o wide
- kubectl get deployments -o wide
- HOST=$(kubectl get nodes kind-worker -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')
- PORT=$(kubectl get service pinger -o jsonpath='{.spec.ports[?(@.port==80)].nodePort}')
- echo $HOST:$PORT
- curl $HOST:$PORT
