language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - main
before_install:
- echo "installing kubectl"
- curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- kubectl version --client
- echo "installing KinD"
- curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
- sudo chmod +x ./kind
- sudo mv ./kind /usr/local/bin/kind
- kind --version
- kind create cluster --config ./kind-config.yaml
- kubectl get nodes
script:
- cd server
- npm install
- node ./index.js