language: node_js
node_js:
- 14
os: ubuntu
branches:
  only:
  - run_simple_service
before_install:
- echo "installing kubectl"
- curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- kubectl version --client
- echo "installing KinD"
- curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
- sudo chmod +x ./kind
- sudo mv ./kind /usr/local/bin/kind
- kind --version
- kind create cluster --config ./kind-config.yaml
- sleep 30s
- kubectl get nodes
script:
- kubectl create deployment nginx --image=nginx
- kubectl create service nodeport nginx --tcp=80:80
- REPS=$(kubectl get deployment nginx -o jsonpath='{.status.availableReplicas}') && while [ $REPS != 3 ]; do REPS=$(kubectl get deployment nginx -o jsonpath='{.status.availableReplicas}'); echo $REPS; sleep 2s; done
- kubectl get svc
- kubectl get pods
- kubectl get deployments
- HOST=$(kubectl get nodes kind-worker -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')
- PORT=$(kubectl get service nginx -o jsonpath='{.spec.ports[?(@.port==80)].nodePort}')
- curl $HOST:$PORT
